
package com.flyonsky.account;

import com.flyonsky.model.Account;
import com.flyonsky.model.FlowDetail;
import com.flyonsky.util.MathUtils;

rule "amount check"
    when
        $account:Account($flowDetails:flowDetailList)
        $total:Double() from accumulate(
            $flowDetail: FlowDetail() from $flowDetails,
            init(Double sumAmount = 0.0D),
            action(
                sumAmount = MathUtils.add(sumAmount,$flowDetail.getCurrentAmount());
            ),
            result(sumAmount)
        )
//        $account:Account(amount == $total)
    then
        System.out.println("detail amount is: " + $total + " amount:" + $account.getAmount());
end